export const QuotationContextResponse = {
  quotation: {
    quotation: {
      quotationId: 0,
      title: "",
      date: "",
      clientId: 0,
      description: "",
      status: 0,
      productType: 0,
      images: [],
      lastEditedByName: "",
    },
    version: {
      quotationVersionId: 0,
      quotationId: 0,
      subDescription: "",
      versionNumber: 0,
      profitMargin: 0,
      profit: 0,
      extraCosts: [],
      productTax: 0,
      laborCost: 0,
      lastEditedByName: "",
      discount: 0,
      subTotal: 0,
      totalCost: 0,
    },
    supplies: [],
    assets: [],
  },
  assetsCatalog: [],
  suppliesCatalog: [],
  productTypes: [],
  quoteStatuses: [],
  costOfElectricity: 0,
};
