export const QuotationContextResponse = {
  quotation: {
    quotation: {
      quotationId: 0,
      title: "",
      date: "",
      clientId: 0,
      description: "",
      status: 0,
      productType: 0,
      images: [],
      lastEditedByName: "",
    },
    version: {
      quotationVersionId: 0,
      quotationId: 0,
      subDescription: "",
      versionNumber: 0,
      profitMargin: 0,
      profit: 0,
      extraCosts: [],
      productTax: 0,
      laborCost: 0,
      lastEditedByName: "",
      discount: 0,
      subTotal: 0,
      totalCost: 0,
    },
    supplies: [],
    assets: [],
    costBreakdown: {
      materialsCost: 0,
      assetsCost: 0,
      laborCost: 0,
      extraCosts: 0,
      baseCost: 0,
      supplies: [],
      profitMargin: 0,
      profit: 0,
      subTotal: 0,
      discount: 0,
      productTax: 0,
      totalCost: 0,
    },
  },
  assetsCatalog: [],
  suppliesCatalog: [],
  productTypes: [],
  quoteStatuses: [],
  costOfElectricity: 0,
};
